Feature/login-page -- 작업 완료
dm-plz/family-farm-mobile pull request #1
Opened 2024-07-26 12:44 UTC by porporpor020202

## PR 체크리스트

PR을 제출하기 전에 아래의 체크리스트를 확인해주세요:
## PR 유형

어떤 종류의 변경 사항인가요? (해당 사항에 모두 체크)

feature/login-page

docs/READEME.md 파일 수정. (초기 생성법, 추가한 라이브러리 적어놓음)

<img width="872" alt="Screenshot 2024-07-26 at 9 43 55 PM" src="https://github.com/user-attachments/assets/b11f0b82-86cf-4d56-ac2e-950eeed4c023">

2024-07-26 12:46 UTC, porporpor020202 commented
마일스톤이 없어요

2024-07-26 15:36 UTC, porporpor020202 commented
src 폴더 alias로 지정하는 거(module-resolver)는 다음 기능 추가할때 수정해놓을께

2024-07-26 16:48 UTC, timepresent95 submitted a review, later dismissed
현재 코멘트 된 내용들 전부 그렇게 중요하지 않아서 다음에 적용하거나 그냥 넘어가도 될 것 같아

대신 2가지 정도 토픽이 있어.

1. eslint 설정 추가하기
- eslint-plugin-react
- eslint-plugin-import
위 두개 추가하고 싶은데 검토 한번 해줘
당장 적용하자는거는 아니야

2. yarn.lock이랑 package-lock.json
두개가 동시에 존재해서 어떤 lock 파일을 따라 사용해야하는지가 헷갈리네
사용하는 쪽으로 선택해줘

화면 구현하느라 고생 많았어

2024-07-26 16:48 UTC, timepresent95 commented on package.json
혹시 4버전 안쓰고 2버전 사용한 이유가 있을까?
https://www.nativewind.dev/v4/getting-started/react-native
최신 버전은 이걸 쓰라고 되어있고 별 다른 문제 없이 사용 가능한것 같은데

2024-07-26 16:48 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +  console.log(isIOS);
테스트용 콘솔은 빼서 최종 PR하면 더 좋을것 같아

2024-07-26 16:48 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +}
별도로 분리해서 관리하는게 더 좋을것 같은데
여기서만 사용된다면 그냥 둬도 상관 없을것 같아
(이건 취향 차이)

2024-07-26 16:48 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +  const isIOS = Platform.OS === 'ios' ? true : false;
```suggestion
  const isIOS = Platform.OS === 'ios'
```
삼항 연산자말고 그냥 조건문으로 표기하는게 더 좋을것 같아

2024-07-26 16:48 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +function LoginPage(): React.JSX.Element {
반환값이 React.JSX.Element라는 사실은 tsx파일에 존재하는걸로 이미 이해할수 있어서
두번 작성하지 않아도 될것 같아

2024-07-27 04:35 UTC, porporpor020202 commented on package.json
V4는 아직 릴리즈 안된거 아녀?
커밍쑨이라고 써있던데

"This is unreleased documentation for NativeWind v4 version.
For up-to-date documentation, see the [latest version](https://www.nativewind.dev/) (v2)."

2024-07-27 04:45 UTC, porporpor020202 commented on package.json
모듈리졸버 관련
- 응 다음 버전에 모듈리졸버 추가할께.

eslint 설정 추가하기 관련
- eslint-plugin-react 이거는 ejlintrc 파일에 이미 설정된거 아냐? react-native꺼로
- eslint-plugin-import 이거는 좋아보이넴. 다음버전에 반영하자

yarn.lock이랑 package-lock.json 관련
- 이거 아마 cli로 만들면 자동으로 생기는 거 같음. 기본 프로젝트 번들링 할 때, yarn이 사용된걸까? 잘 모르겠넴
- 나는 yarn 안쓰고 npm으로만 작업중이야.

-- 고마웡

2024-07-27 04:45 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +  console.log(isIOS);
어머 이런게 있었네

2024-07-27 04:46 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +  console.log(isIOS);
그럼 이거 PR취소하고 다시 PR 올리는게 맞는 절차인가?

2024-07-27 04:49 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +}
지금은 시현이도 여기 둬도 상관없다고 했으니 둬보자. 만약 더 복잡해지면 그때 옮겨보자. 일단 디자인 파일 나와야 어떻게 할지 결정이 될듯

2024-07-27 04:50 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +  const isIOS = Platform.OS === 'ios' ? true : false;
아 그러네 바꿔야겠다 나 이거 왜 이걸로 만들었지

2024-07-27 04:51 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +function LoginPage(): React.JSX.Element {
아 그렇구나 중복이네 제거할께욤

2024-07-27 14:27 UTC, timepresent95 commented on package.json
native wind v4 문서 윗부분을 못봤네
사람들이 쓰는거랑 최신 tailwind 적용하려면 쓰라는것만 봤다
이해했어!! 확인 고마워

2024-07-27 15:09 UTC, timepresent95 commented on package.json
두개가 각각 가지고 있는게 다르다고 조사를 했었는데
[여기](https://github.com/facebook/react-native/blob/8fe3ae3ccc7777dfc505bc62375eb4156e7dac18/packages/eslint-config-react-native/package.json) 보니까 모듈 리졸버에 eslint-plugin-react가 eslint-plugin-import에 들어있네

미안... 머쓱 요즘 자주 이러네 좀 더 꼼꼼히 확인해볼게

2024-07-27 15:13 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +  console.log(isIOS);
우선 결론만 말하면 형 편할대로 하면돼

아래는 구체적 설명이야.

![Screenshot 2024-07-28 at 00 10 27](https://github.com/user-attachments/assets/78ddf75f-0d53-4689-beae-5f5069b7b053)

이게 review 내용에 대해서 최종적으로 고르는 선택지인데
approve는 나랑 더 대화하지 않고 형에게 맡긴다는 뜻이고

comment는 약간 적용하길 희망하니까 이야기해보자
request changes는 적용하길 강하게 원하니까 이야기해보자
라는 뜻으로 받아주면 될것같아!

2024-07-27 15:14 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +}
우리 디자인은 대충 나왔고 일요일에 말할거긴 하지만 notion wbs일정 준수하면서 할 수 있게 작업 나눠서 하려고 생각중이야.

물론 완전한 디자인은 아니고 화면 해설서 정도라서 디자이너가 디자인 해주면 다시 한 번 하긴 해야할거야

2024-07-27 15:14 UTC, timepresent95 commented on src/component/LoginPage.tsx
> +  const isIOS = Platform.OS === 'ios' ? true : false;
나도 자주 그래 ㅋㅋㅋㅋㅋ 뭔가 조건 들어가면 삼항 연산자부터 찾는 js 개발자들 ㅋㅋㅋㅋㅋㅋㅋ

2024-07-29 00:49 UTC, porporpor020202 commented on package.json
오 나도 몰랐다. "eslint-plugin-react"랑 ""eslint-plugin-react-native"랑 그냥 다른 패키지인줄만 알았는데
두개가 짬뽕되있는거였네.

근데 모듈 리졸버는 무슨 말이야? 모듈 리졸버에 eslint-plugin이 있는겨?

글고 나도 덕분에 한번 더 생각해보고 배우게 되니까, 이게 팀의 장점인듯? 오히려 시너지나고 좋은거지 미안할게 아닌듯

2024-07-29 00:57 UTC, porporpor020202 commented on src/component/LoginPage.tsx
> +  const isIOS = Platform.OS === 'ios' ? true : false;
덕분에 코드 문제점이 하나씩 보인다 ㅋㅋㅋ

2024-07-29 11:34 UTC, timepresent95 requested changes
몇가지 수정이 필요할것 같아
1.
우선 이슈를 2개의 PR에 재사용하지말아줘. 진행중으로 PR에 표기하는게 아니라
이번 PR에 들어갈 내용이 무엇인지 명확히 전달되어야 내가 그걸 기준으로 리뷰가 가능해
2.
저번 리뷰에도 이야기했던 주석 제거 같은게 전혀 안되었어
이 부분 주의해서 PR 요청 전에 꼭 커밋 내용 전부 확인 해줘
3.
css가 Figma 기준이 아닌것 같아 보이는 코드가 있어서 확인해보니
Figma에서 css를 볼 수 없는 상황이던라고
가은누나한테 내가 요청해둘테니
Figma 기준으로 정확히 스타일링해주면 고마울것 같아

2024-07-29 11:34 UTC, timepresent95 commented on .env
> +TEST_URL = "gooman.com"
커밋, PR 전에 테스트를 위한 코드는 최대한 제거해줘
만약 남겨둬야하면 PR 생성할 때 해당 내용에 대해서 작성 부탁해

2024-07-29 11:34 UTC, timepresent95 commented on src/component/Button.tsx
> +  console.log('클넴', className);
console 지워줘

2024-07-29 11:34 UTC, timepresent95 commented on src/component/sign-up-page/SignUpPageHeader.tsx
Figma에는 텍스트 색이 변경되는게 없는데 왜 코드에는 해당 내용이 있는거야?

2024-07-29 11:34 UTC, timepresent95 commented on src/component/sign-up-page/SignUpPageHeader.tsx
> +        <Text className="mt-2 text-green-600">가족 면접</Text>
가족 연결을 잘못 작성한것 같아

2024-07-29 11:34 UTC, timepresent95 commented on src/pages/LoginPage.tsx
이 페이지는 아직 작업이 안된거 맞지?

2024-07-29 11:34 UTC, timepresent95 commented on src/pages/sign-up/SinUpInformationPage.tsx
> +                <Button className="2123213">아빠</Button>
이거 클래스명이 조금 이상한것 같아

2024-07-29 11:50 UTC, timepresent95 commented
> 3. css가 Figma 기준이 아닌것 같아 보이는 코드가 있어서 확인해보니 Figma에서 css를 볼 수 없는 상황이던라고 가은누나한테 내가 요청해둘테니 Figma 기준으로 정확히 스타일링해주면 고마울것 같아

이 내용 확인해보니까 Figma 권한 상관 없이 우리가 지금 당장 구체적인 수치를 볼 수 없어서 그냥 요소만 넣으면 될것 같네
css 부분은 디자인 정확히 나오기 전까지 크게 이야기하지 않는걸로 하자

2024-07-29 11:51 UTC, timepresent95 commented on src/component/sign-up-page/SignUpPageHeader.tsx
이것도 Figma에서 css 볼수 없는 상황이니까 넘어가면 될것 같아

2024-07-29 11:52 UTC, timepresent95 commented
페이지 번호 같은 경우에는 가은누나가 작업 진행한 뒤에 알려주기로 해서
해당 작업 마무리되면 [이슈 #3](https://github.com/dm-plz/family-farm-mobile/issues/3) 에 반영해주면 될것 같아

2024-07-29 12:22 UTC, porporpor020202 commented on .env
> +TEST_URL = "gooman.com"
몇가지 수정이 필요할것 같아
1.
우선 이슈를 2개의 PR에 재사용하지말아줘. 진행중으로 PR에 표기하는게 아니라
이번 PR에 들어갈 내용이 무엇인지 명확히 전달되어야 내가 그걸 기준으로 리뷰가 가능해


### **PR하나에는 관련된, 그리고 완료된 이슈만 적어달라는 말이지?**



2.
저번 리뷰에도 이야기했던 주석 제거 같은게 전혀 안되었어
이 부분 주의해서 PR 요청 전에 꼭 커밋 내용 전부 확인 해줘

### **주석 제거라면 어떤거? console.log() 말하는건가?**

3.
css가 Figma 기준이 아닌것 같아 보이는 코드가 있어서 확인해보니
Figma에서 css를 볼 수 없는 상황이던라고
가은누나한테 내가 요청해둘테니
Figma 기준으로 정확히 스타일링해주면 고마울것 같아

### **피그마 기준으로 왜 스타일링을 해야해? 디자인 파일 나오면 바뀌는거 아냐? 색깔이나 굵기 이런건 내 마음대로 했는디**

2024-07-29 12:25 UTC, porporpor020202 commented on src/component/Button.tsx
> +  console.log('클넴', className);
이거 원래대로라면 PR에 같이 안올라가는 코드야.
원래대로라면 내가 feature/sing-up-page 라고 브랜치 만들어서 작업했어야 하는 코드지.
이 부분은 아직 개발중인 코드인건데, 아예 그냥 다 제거해버리고 PR 다시 올릴까?
feature/sing-up-page 부분은 다 지우고 말이야.

2024-07-29 12:26 UTC, porporpor020202 commented on src/component/sign-up-page/SignUpPageHeader.tsx
아직 개발중인 코드라서 내가 테스트해본거기도 하고,
그리고 왜 Figma기준으로 작업이 되야해??

2024-07-29 12:26 UTC, porporpor020202 commented on src/component/sign-up-page/SignUpPageHeader.tsx
> +        <Text className="mt-2 text-green-600">가족 면접</Text>
이것도 아직 개발중인 코드.. feature/sing-up-page에 올라갔어야 하는 코드

2024-07-29 12:27 UTC, porporpor020202 commented on src/pages/LoginPage.tsx
이거는 이대로 작업 끝낸거야

2024-07-29 12:27 UTC, porporpor020202 commented on src/pages/sign-up/SinUpInformationPage.tsx
> +                <Button className="2123213">아빠</Button>
이것도 feature/sing-up-page 여기에 들어갔어야 할 코드.

2024-07-29 12:29 UTC, porporpor020202 commented
가은이가 페이지 번호 수정하면, 따로 이슈를 발행할 필요는 없고, #3에서 페이지 넘버만 바꾸면 될까?

2024-07-29 12:30 UTC, porporpor020202 commented
feature/sing-up-page에 들어갔어야 하는 코드들은 아예 지우고 다시 PR 올릴까?

2024-07-29 12:37 UTC, timepresent95 commented on .env
> +TEST_URL = "gooman.com"
1. 맞아
2. 응응 console.log를 비롯해서 필요 없는 내용들은 전부 지워주면 될것같아. 나중에 찾아서 지우려면 놓치는게 많아지거든
3. 이거는 마음대로 각자 하면 싱크가 안맞아서 최소한의 기준으로 Figma를 쓰려고 했는데 이것도 여의치 않아서 그냥 지금처럼 알아볼수 있을정도로 하면 될것같아.

2024-07-29 12:38 UTC, timepresent95 commented on src/component/Button.tsx
> +  console.log('클넴', className);
다 지운다는게 무슨 의미인지 모르겠어 처음부터 다시 개발한다는걸까?

2024-07-29 12:38 UTC, timepresent95 commented on src/pages/LoginPage.tsx
이 페이지가 피그마 어디에 있어?

2024-07-29 12:40 UTC, timepresent95 commented
Q: feature/sing-up-page에 들어갔어야 하는 코드들은 아예 지우고 다시 PR 올릴까?
A: 이건 그렇게 해주면 더 편하긴 하지

Q: 가은이가 페이지 번호 수정하면, 따로 이슈를 발행할 필요는 없고, #3에서 페이지 넘버만 바꾸면 될까?
A: feature/sing-up-page에 들어갔어야 하는 코드를 지우고 작업한다면 페이지 넘버만 바꾸면 되고
그런게 #3에 넘버 바꾸고 새로운 이슈도 발행한뒤 작업해야해

2024-07-29 23:13 UTC, closed without merging