Feat: Feature/question 구현 완료
dm-plz/family-farm-mobile pull request #41
Opened 2024-08-23 04:58 UTC by porporpor020202

- [ ] 버그 수정 (기존 문제를 수정)
- [x] 기능 추가 (새로운 기능)
- [ ] 코드 스타일 수정 (포맷팅, 세미콜론 수정 등, 논리적 변경 없음)
- [ ] 리팩토링 (기능 수정 없이 코드 리팩토링)
- [ ] 문서 수정 (문서 추가 또는 수정)
- [ ] 테스트 추가 (기존 코드에 대한 테스트 추가)
- [x] 빌드 또는 CI 관련 변경 사항

## 해결하려는 문제가 무엇인가요?
* UI 구현

## 첨부 내용

<img width="294" alt="QNAA-01" src="https://github.com/user-attachments/assets/d5bb97a3-2678-45b1-a1b1-a7a01b2fb534">
<img width="301" alt="QNAA-02" src="https://github.com/user-attachments/assets/592c3e16-2a17-4d33-8f73-e252c7a9e44b">
<img width="287" alt="QNAA-03" src="https://github.com/user-attachments/assets/c9de84aa-cf87-444e-8219-a94d35ea56b3">
<img width="329" alt="QNAA-04" src="https://github.com/user-attachments/assets/b31414a0-0c75-469d-b46a-118a9059fd05">
<img width="307" alt="QNAA-04(Image)" src="https://github.com/user-attachments/assets/0370811a-0a73-4c95-8241-65d435dcca40">

## 이슈

resolves #32
resolves #33 
resolves #34

2024-08-23 16:16 UTC, timepresent95 commented
Edit 관련 내용들이 전부 누락된것같아~

2024-08-24 11:58 UTC, porporpor020202 commented
> Edit 관련 내용들이 전부 누락된것같아~

Edit이 어떤거 말하는거야? 구현해야하는 페이지 말하는건가 싶어서 다시 봤는데 이건 아닌거같구.. 어떤거?

2024-08-26 00:38 UTC, timepresent95 commented
@porporpor020202  이거 작업중일까?

2024-08-26 15:04 UTC, porporpor020202 commented
완료~~ 근데 이슈 밑에 이상한 물음표가 도통 안없어진다

2024-08-26 16:32 UTC, timepresent95 commented
@porporpor020202 
이슈 밑에 물음표는 bs라고 형 키보드 입력 중에 backspace로 지우면 남는 input 값이 남아서 그래
한번 더 지우면 돼

<br/> 오른쪽에 있었고 
확인해보고 싶으면 vscode에 이전 버전 내용 전부 복사해서 붙여넣으면 보여

일단 내가 지워둘게

2024-08-26 17:42 UTC, timepresent95 requested changes
빠르게 작업해줘서 고마워~
리뷰 내용 읽고 적용할 사항들 적용 부탁할게!

2024-08-26 17:42 UTC, timepresent95 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
use라는 prefix는 react 문법에서 hook 사용할때 사용하는걸로 정해져있는거라서
이렇게 사용하면 나중에 혼란스러울것같아 수정하는게 좋을것같아
그냥 dayjs라고 불러와도 돼~

2024-08-26 17:42 UTC, timepresent95 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
Question으로 파일 이름 수정해야해 (e빠짐)

2024-08-26 17:42 UTC, timepresent95 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
> +    } else {
tabBarStyle이 적용되지 않는 이유는
BottomTabNavigationProp를 써야하는데 StackNavigationProp를 type으로 제공하고 있어서야
QustionAnswerStackNavigator는 BottomTabNavigator.tsx 에서 사용중이니까
props로 넘어오는 navigation은 BottomTabNavigator지

추가로 이런건 BUG는 아니야. 동작이 안되면 BUG고 FIXME나 XXX같이 동작은 한다는 의미를 담아서 표기해줘

2024-08-26 17:42 UTC, timepresent95 commented on src/pages/question-answer/AnswerWithFeeling.tsx
> +            {/* BUG: 이모지 탈모 해결해야함 */}
line-height 문제인데 이건 css 설정할때 고치면 될것같아

2024-08-26 17:42 UTC, timepresent95 commented on src/pages/question-answer/ViewAnswer.tsx
> +          {/* BUG:  break-words 속성 안먹음. 해결해야함.*/}
https://reactnative.dev/docs/text#textbreakstrategy-android

여기 들어가면 android랑 ios에 각각 적용 가능한 내용 있어

보다 안정적으로 하는 방법은 조금 더 찾아보면 좋을것 같아

2024-08-26 17:42 UTC, timepresent95 commented on src/pages/question-answer/ViewAnswer.tsx
> +// BUG: Sending 'onAnimatedValueUpdate' 해결해야함. (네비게이션 로직 확정 할 수 있을때 작업예정 (be))
이거 무슨 내용인지 조금 더 자세히 설명좀 부탁할게
잘 모르겠어

2024-08-26 18:08 UTC, timepresent95 commented
이슈 38 39 40도 같이 닫히게 하면 좋을것 같아

2024-08-27 06:54 UTC, porporpor020202 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
이거 근데 이렇게 사용해야하는 이유 좀 더 찾아보려고 했는데 안나오더라.
"dayjs 인스턴스로 사용" 이런 비슷한 키워드로 검색해봤었거든?
트리 쉐이킹 내용도 검색해봤는데 자료를 못찾겠더라. 나중에 시간되면 관련 내용 공유좀 해줄 수 있을까? 네이밍은 고쳐놓을께

2024-08-27 07:00 UTC, porporpor020202 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
상당히 많이 빠진거 발견

2024-08-27 07:15 UTC, porporpor020202 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
> +    } else {
오 고맙당
문제는 바꿨는데도 해결이 안된당.
일단 FIXME로 수정해놓을께.

2024-08-27 07:15 UTC, porporpor020202 commented on src/pages/question-answer/AnswerWithFeeling.tsx
> +            {/* BUG: 이모지 탈모 해결해야함 */}
땡큐. 이것도 FIXME로 수정해놓을께

2024-08-27 07:18 UTC, porporpor020202 commented on src/pages/question-answer/ViewAnswer.tsx
> +          {/* BUG:  break-words 속성 안먹음. 해결해야함.*/}
땡큐 고마웡
이거 디자인 입힐때 해결해야할거같아.
디자인파일 보면, 줄 바뀜 될 때, bold 처리가 들어가더라고, 이거 만들면서 같이 해야할듯
이것도 FIXME로 수정해놓을께

2024-08-27 07:19 UTC, porporpor020202 commented on src/pages/question-answer/ViewAnswer.tsx
> +          {/* BUG:  break-words 속성 안먹음. 해결해야함.*/}
아 아닌가? 이건 진짜 작동 안하니까 버그인가?

2024-08-27 07:20 UTC, porporpor020202 commented on src/pages/question-answer/ViewAnswer.tsx
> +// BUG: Sending 'onAnimatedValueUpdate' 해결해야함. (네비게이션 로직 확정 할 수 있을때 작업예정 (be))
아 이거 ios 시뮬에서 테스트하다보면 간헐적으로 Sending 'onAnimatedValueUpdate' 워닝이 뜨더라고. 시뮬레이터에서.
이거 문제 해결 계속 해보다가, 결국 시간내에 화면 구현이 안될거같아서 일단 bug로 올렸었어.
이것도 FIXME로 수정해놓을께

2024-08-27 07:22 UTC, porporpor020202 commented
> 이슈 38 39 40도 같이 닫히게 하면 좋을것 같아

본문 업데이트 했어~
코드 리뷰해줘서 고마워 많이 배웠어

2024-08-27 08:04 UTC, timepresent95 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
![Screenshot 2024-08-27 at 17 03 02](https://github.com/user-attachments/assets/7a5e9d04-3cc0-45fc-9253-acb198802cb5)
첨부 이미지처럼 dayjs에 일부 기능은 plugin을 extend해야하만 사용 가능한데

항상 dayjs 라이브러리 자체를 호출해서 사용하는 방식을 사용하면
plugin을 import하는것과 extend를 위한 코드를 해당 기능을 사용하는 모든곳에 작성해줘야해

그런데 지금처럼 dayjs.ts 파일에서 이러한 모든걸 처리한 뒤에 export해서 사용하면
한곳에서 관리가 가능해서
plugin을 제거하거나 대치하기 편해서
이렇게 사용하자고 제안한거야

필수는 아니고 선택~

2024-08-27 08:05 UTC, timepresent95 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
또 있었어? ㅋㅋㅋ 우리 오타도 서로 잘 봐주자
내 코드에 아마 엄청 많을걸 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-08-27 08:07 UTC, timepresent95 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
> +    } else {
해결이 안된건 아마 nonShowBottomTab을 선언할때 타입을 단순 추론으로 열어둬서 그럴거야
이걸 좀더 닫힌 추론으로 적용할수 있도록 as const를 붙이면 될거야

else에 있는 다른애도 동일하게 적용하면 돼

(단순 추론, 닫힌 추론 말고 정식 명칭이 기억이 안나네;; 이건 gpt한테 물어봐봐)

2024-08-27 08:07 UTC, porporpor020202 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
아~~~~ 땡큐

2024-08-27 08:07 UTC, timepresent95 commented on src/pages/question-answer/ViewAnswer.tsx
> +          {/* BUG:  break-words 속성 안먹음. 해결해야함.*/}
이것도 XXX에 가까운것 같아
정상 작동은 되잖아 (글자가 안보이지 않으므로)

디자인때 하는거 동의야~

2024-08-27 08:09 UTC, timepresent95 commented on src/pages/question-answer/ViewAnswer.tsx
> +// BUG: Sending 'onAnimatedValueUpdate' 해결해야함. (네비게이션 로직 확정 할 수 있을때 작업예정 (be))
이거 문제 발생될때 상황이랑 이미지 + 콘솔 문구 전체 해서 이슈 만들어주면 좋을것같아

2024-08-27 08:11 UTC, porporpor020202 commented
아 이거 oauth pr되면서 컨플릭 낫네. pull 해서 다시 pr 올릴께

2024-08-27 08:44 UTC, porporpor020202 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
<img width="454" alt="Screenshot 2024-08-27 at 5 40 33 PM" src="https://github.com/user-attachments/assets/e2ec352f-4e2d-4b08-8d36-568caf58cd5c">

이 오류 때문에,
instanceDayjs 로 네이밍할께.

2024-08-27 08:46 UTC, porporpor020202 commented
> 아 이거 oauth pr되면서 컨플릭 낫네. pull 해서 다시 pr 올릴께

완료함.

2024-08-27 09:22 UTC, porporpor020202 commented on src/navigations/stack/QustionAnswerStackNavigator.tsx
> +    } else {
요 부분은 내가 타입스크립트 공부해보면서 해결해볼께 키워드 고마워

2024-08-27 09:23 UTC, porporpor020202 commented on src/pages/question-answer/ViewAnswer.tsx
> +          {/* BUG:  break-words 속성 안먹음. 해결해야함.*/}
변경완료~

2024-08-27 09:25 UTC, porporpor020202 commented on src/pages/question-answer/ViewAnswer.tsx
> +// BUG: Sending 'onAnimatedValueUpdate' 해결해야함. (네비게이션 로직 확정 할 수 있을때 작업예정 (be))
만들어둘께

2024-08-27 11:03 UTC, timepresent95 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
import를 변경하는게 더 좋지 않을까?

import _dayjs from 'dayjs'

한 다음 const dayjs ~

2024-08-27 11:05 UTC, timepresent95 approved these changes, later dismissed
dayjs는 수정하고싶으면 하면 될것같아
어차피 export default로 내보내서 import 할때 원하는 이름으로 하면 되는거라

2024-08-27 13:35 UTC, porporpor020202 commented on src/pages/question-answer/QuestionList.tsx
> +import useDayjs from '@/util/dayjs';
아 이런 방식이 있네 이렇게 바꿔둘께~

2024-08-27 13:42 UTC, porporpor020202 commented
> dayjs는 수정하고싶으면 하면 될것같아 어차피 export default로 내보내서 import 할때 원하는 이름으로 하면 되는거라

위에 알려준 방식으로 수정했어

2024-08-27 15:00 UTC, timepresent95 approved these changes

2024-08-28 04:00 UTC, porporpor020202 reviewed
.

2024-08-28 04:00 UTC, merged